name = "nlopt-f"
version = "0.2.0"
license = "MIT"
maintainer = ["@awvwgk", "@ivan-pi"]
author = ["Sebastian Ehlert"]
description = "Interface to NLopt library"
keywords = ["nlopt"]
copyright = "Copyright 2021-2022 S. Ehlert, I. Pribec"

[build]
link = "nlopt"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
