name = "nlopt-f"
version = "0.1.0"
license = "MIT"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
description = "Interface to NLopt library"
keywords = ["nlopt"]
copyright = "Copyright 2021 S. Ehlert"

[build]
link = "nlopt"

[dev-dependencies]
test-drive.git = "https://github.com/awvwgk/test-drive"
